function caminhoBase(){return location.pathname.includes('/paginas/')?'../':''}
function aplicarConfiguracoes(config){document.body.classList.remove('tema-calmo','tema-foco','tema-escuro','tema-altoContraste','fonte-grande','fonte-muito-grande','sem-distracoes');if(config.tema&&config.tema!=='padrao')document.body.classList.add('tema-'+config.tema);if(config.fonte&&config.fonte!=='normal')document.body.classList.add('fonte-'+config.fonte);if(config.semDistracoes)document.body.classList.add('sem-distracoes')}
function carregarConfiguracoes(){const salva=localStorage.getItem('focusTeaConfig');const config=salva?JSON.parse(salva):{};aplicarConfiguracoes(config);if(document.getElementById('tema')){tema.value=config.tema||'padrao';fonte.value=config.fonte||'normal';semDistracoes.checked=!!config.semDistracoes;reducaoAnimacoes.checked=!!config.reducaoAnimacoes}}
function salvarConfiguracoes(){const config={tema:tema.value,fonte:fonte.value,semDistracoes:semDistracoes.checked,reducaoAnimacoes:reducaoAnimacoes.checked};localStorage.setItem('focusTeaConfig',JSON.stringify(config));aplicarConfiguracoes(config);statusConfig.textContent='Configurações salvas com sucesso!'}
function tarefas(){return JSON.parse(localStorage.getItem('tarefasFocusTea')||'[]')}
function salvarTarefas(lista){localStorage.setItem('tarefasFocusTea',JSON.stringify(lista));atualizarProgresso()}
function renderizarTarefas(){const lista=document.getElementById('listaTarefas');if(!lista)return;const dados=tarefas();lista.innerHTML='';dados.forEach((t,i)=>{const div=document.createElement('div');div.className='task';div.innerHTML=`<input type="checkbox" ${t.feita?'checked':''} onchange="alternarTarefa(${i})"><span>${t.texto}</span>`;lista.appendChild(div)})}
function adicionarTarefa(){const input=document.getElementById('novaTarefa');if(!input.value.trim())return;const dados=tarefas();dados.push({texto:input.value.trim(),feita:false});salvarTarefas(dados);input.value='';renderizarTarefas()}
function alternarTarefa(i){const dados=tarefas();dados[i].feita=!dados[i].feita;salvarTarefas(dados);renderizarTarefas()}
function gerarRotinaIA(){const rotina=[{texto:'Revisar conteúdo por 20 minutos',feita:false},{texto:'Fazer 3 exercícios',feita:false},{texto:'Pausa sensorial de 10 minutos',feita:false},{texto:'Organizar material para amanhã',feita:false}];salvarTarefas(rotina);renderizarTarefas()}
function atualizarProgresso(){const dados=tarefas();const total=dados.length;const feitas=dados.filter(t=>t.feita).length;const pct=total?Math.round((feitas/total)*100):0;const texto=document.getElementById('progressoTexto');const barra=document.getElementById('progressoBarra');if(texto)texto.textContent=pct+'%';if(barra)barra.style.width=pct+'%'}
const materias={fotossintese:{titulo:'🌱 Fotossíntese',texto:'A fotossíntese é o processo em que as plantas usam luz solar, água e gás carbônico para produzir energia.'},matematica:{titulo:'➗ Matemática',texto:'Na matemática, resolver um problema fica mais fácil quando dividimos a questão em partes menores.'},historia:{titulo:'🏛️ História',texto:'História estuda acontecimentos do passado para entender melhor a sociedade atual.'}}
function mudarMateria(){const box=document.getElementById('conteudoEstudo');if(!box)return;const m=materias[materia.value];box.innerHTML=`<h2>${m.titulo}</h2><p>${m.texto}</p>`}
function responderIA(){const pergunta=document.getElementById('perguntaIA').value;respostaIA.textContent=pergunta?'Explicação adaptada: vamos entender isso em passos simples, com calma e exemplos.':'Digite uma dúvida para a IA responder.'}
function corrigirExercicio(){const marcada=document.querySelector('input[name="q1"]:checked');feedback.textContent=!marcada?'Escolha uma alternativa.':marcada.value==='certa'?'Muito bem! Você acertou.':'Quase! Tente lembrar que fotossíntese acontece nas plantas.'}
document.addEventListener('DOMContentLoaded',()=>{carregarConfiguracoes();renderizarTarefas();atualizarProgresso();mudarMateria()})
